### ISSUE TITLE
Update documentation about ELK credentials setup

### ISSUE THREAD

**Issue by jemacchi** [geosolutions-it/analytics#13]
It's required to update documentation, scripts and references about how to set the ELK credentials, so it's clearly defined in the repository.

**Comment by lpasquali** [comment]
@jemacchi @randomorder 
I agree, but this would be better fit in a chapter about sizing, configuring, deploying elasticsearch (which is not covered at all as we are covering actually a bunch of elastic clients (kibana, logstash, filebeat).
Also accounting procedures change in between environments (kubertes, docker, bare metal, cloud server elastic instance) by the way I think that we could just document it like [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-put-user.html):
```
POST /_security/user/jacknich
{
  "password" : "j@rV1s",
  "roles" : [ "admin", "other_role1" ],
  "full_name" : "Jack Nicholson",
  "email" : "jacknich@example.com",
  "metadata" : {
    "intelligence" : 7
  }
}
```

**Comment by lpasquali** [comment]
docs updated

https://github.com/geosolutions-it/analytics/blob/master/README.md
